# Generated by Django 4.2.28 on 2026-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiminishedValueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_date', models.DateField(db_index=True, editable=False)),
                ('created_year', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_month', models.PositiveIntegerField(db_index=True, editable=False)),
                ('client', models.CharField(blank=True, db_index=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(blank=True, db_index=True, max_length=255)),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('loss_date', models.DateField(blank=True, db_index=True, null=True)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('appraiser', models.CharField(blank=True, max_length=255)),
                ('vehicle_year', models.CharField(blank=True, db_index=True, max_length=10)),
                ('vehicle_make', models.CharField(blank=True, db_index=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, db_index=True, max_length=100)),
                ('vehicle_trim', models.CharField(blank=True, max_length=100)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=50)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=50)),
                ('color_trim', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, db_index=True, max_length=50)),
                ('loss_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('repair_facility', models.CharField(blank=True, max_length=255)),
                ('repair_total', models.FloatField(default=0)),
                ('preloss_value', models.FloatField(default=0)),
                ('base_loss_pct', models.FloatField(default=0)),
                ('damage_modifier', models.FloatField(default=0)),
                ('mileage_modifier', models.FloatField(default=0)),
                ('other_modifier', models.FloatField(default=0)),
                ('damage_description', models.TextField(blank=True)),
                ('base_dv', models.FloatField(db_index=True, default=0)),
                ('adjusted_dv', models.FloatField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Diminished Value Report',
                'verbose_name_plural': 'Diminished Value Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='documents_d_created_de64ee_idx'), models.Index(fields=['created_year'], name='documents_d_created_92460d_idx'), models.Index(fields=['created_month'], name='documents_d_created_d9e1ba_idx'), models.Index(fields=['created_year', 'created_month'], name='documents_d_created_a0bed1_idx'), models.Index(fields=['client'], name='documents_d_client_fba4e6_idx'), models.Index(fields=['claim_number'], name='documents_d_claim_n_2a8dbb_idx'), models.Index(fields=['vin'], name='documents_d_vin_15b5dd_idx'), models.Index(fields=['vehicle_make'], name='documents_d_vehicle_b8d0df_idx'), models.Index(fields=['loss_date'], name='documents_d_loss_da_717f1d_idx'), models.Index(fields=['report_date'], name='documents_d_report__782c85_idx')],
            },
        ),
    ]
