# Generated by Django 4.2.28 on 2026-02-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diminishedvaluereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_created_a0bed1_idx',
        ),
        migrations.AddField(
            model_name='diminishedvaluereport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='dv_reports/'),
        ),
        migrations.AddField(
            model_name='diminishedvaluereport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='diminishedvaluereport',
            index=models.Index(fields=['report_number'], name='documents_d_report__726338_idx'),
        ),
    ]
