# Generated by Django 4.2.28 on 2026-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_diminishedvaluereport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diminishedvaluereport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_created_de64ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_created_92460d_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_created_d9e1ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_client_fba4e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_claim_n_2a8dbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_vin_15b5dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_vehicle_b8d0df_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_loss_da_717f1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_report__782c85_idx',
        ),
        migrations.RemoveIndex(
            model_name='diminishedvaluereport',
            name='documents_d_report__726338_idx',
        ),
        migrations.AddField(
            model_name='diminishedvaluereport',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='diminishedvaluereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20),
        ),
    ]
